services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: wb-parser-app
        ports:
            - "8000:8000"
        volumes:
            - .:/var/www/html
        environment:
            DB_HOST: mysql
            DB_PORT: ${DB_PORT}
            DB_DATABASE: ${DB_DATABASE}
            DB_USERNAME: ${DB_USERNAME}
            DB_PASSWORD: ${DB_PASSWORD}
        depends_on:
            - mysql
        networks:
            - wb-network

    mysql:
        image: mysql:9.0-oracle
        container_name: wb-parser-mysql
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        volumes:
            - mysql_data:/var/lib/mysql
            - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
        ports:
            - "${DB_PORT:-3306}:3306"
        networks:
            - wb-network
        healthcheck:
            test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
            interval: 10s
            timeout: 5s
            retries: 3

volumes:
    mysql_data:

networks:
    wb-network:
        driver: bridge
