services:
    mysql:
        image: mysql:9.0-oracle
        container_name: wb-parser-mysql
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        volumes:
            - mysql_data:/var/lib/mysql
        ports:
            - "${DB_PORT:-3306}:3306"
        networks:
            - wb-network
        healthcheck:
            test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
            interval: 10s
            timeout: 5s
            retries: 3

    redis:
        image: redis:alpine
        container_name: wb-parser-redis
        ports:
            - "${REDIS_PORT:-6379}:6379"
        volumes:
            - redis_data:/data
        networks:
            - wb-network
        healthcheck:
            test: [ "CMD", "redis-cli", "ping" ]
            interval: 10s
            timeout: 5s
            retries: 3

volumes:
    mysql_data:
    redis_data:

networks:
    wb-network:
        driver: bridge
